### ISSUE TITLE
angle model input size

### ISSUE THREAD

**Issue by harhar539** [FeiGeChuanShu/ncnn_paddleocr#1]
Thx for the ncnn model. All model works well except the angle model in chineseocr_lite. Base on chineseocr_lite, I change input size of angel model from 192*32*3 ---> 192*48*3, but the softmax output is all 1 value. I check that the input img of getAngle func is OK. Is there any other preprocess should be done for angel model? The mean and norm vals chineseocr_lite in are right?

**Comment by FeiGeChuanShu** [comment]
@harhar539 there's nothing different but dstHeight and softmax output. If this angle model output angle index is 1 means it should rotate 180.

**Comment by harhar539** [comment]
Thanks for your reply. Angle rotation is correct when softmax output is fixed.

**Comment by soham24** [comment]
@FeiGeChuanShu can we have inference code to run angle model too ?
@harhar539  can help ?
