### ISSUE TITLE
请问支持windows cpu推理吗

### ISSUE THREAD

**Issue by Dandelion111** [FeiGeChuanShu/ncnn_paddleocr#3]
请问支持windows推理吗？ ncnn框架在windows cpu上有优势吗，相对于ppocr原来的paddle推理框架

**Comment by FeiGeChuanShu** [comment]
Windows CPU上ncnn没优势，可以试试openvino

**Comment by Dandelion111** [comment]
> Windows CPU上ncnn没优势，可以试试openvino

正在研究openvino推理paddle模型，请问您有这方面的经验吗？

**Comment by FeiGeChuanShu** [comment]
转成onnx再转openvino即可，之前试过可以的

**Comment by Dandelion111** [comment]
> 转成onnx再转openvino即可，之前试过可以的

我也是先转onnx再转openvino的，但是推理的结果完全不对，输出的shape和paddle推理的不一样，请问在转的时候有什么需要注意的吗?输入的shape是固定的吗？
