### ISSUE TITLE
模型转换问题

### ISSUE THREAD

**Issue by ChaoII** [FeiGeChuanShu/ncnn_paddleocr#7]
飞哥，请问一下，这里面的paddleocr的飞桨模型可以直接转ncnn么，也就是不依赖于paddleocr2pytorch这个转换过程。当初直接用paddle2onnx onnxsimply onnx2ncnn 识别模型转化不成功。飞哥怎么看

**Comment by FeiGeChuanShu** [comment]
可以直接paddle2onnx2ncnn，问题不大

**Comment by ChaoII** [comment]
> 可以直接paddle2onnx2ncnn，问题不大

飞哥，我转化成onnx没问题，就是onnx2ncnn搞不定，麻烦飞哥能够重现一下。给个婴儿都能看懂教程嘛。

**Comment by ChaoII** [comment]
close
